### Create orders
// Create an amount of orders, e.g. 100
POST {{baseurl}}/order/1000
Content-Type:

### Get order amount
// Get the amount of orders
GET {{baseurl}}/order/count
Accept: application/json

### Stream Orders to Client
// Stream a certain amount of orders created in a time range
GET {{baseurl}}/order?From=2020-01-01T00%3A00%3A00Z&To=2024-01-01T00%3A00%3A00Z&Amount=1000
Accept: */*;application/json;application/octet-stream

### Streams Orders to Block Blob
// Upload a certain amount of orders, that were created in a certain time range, to a blob, one order per blob block.
POST {{baseurl}}/etl?From=2020-01-01T00%3A00%3A00Z&To=2024-01-01T00%3A00%3A00Z&Amount=1000
Accept: */*;application/json;application/octet-stream

### Streams Orders to Block Blob - Space Efficient
// Upload a certain amount of orders, that were created in a certain time range, to a blob, filling up each blob block to the max before starting a new one.
POST {{baseurl}}/etlefficient?From=2020-01-01T00%3A00%3A00Z&To=2024-01-01T00%3A00%3A00Z&Amount=1000
Accept: */*;application/json;application/octet-stream

###